// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pojsfjklyzknysxidjls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvanNmamtseXprbnlzeGlkamxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MTU5NjcsImV4cCI6MjA3MTQ5MTk2N30.kHerCUwEATtxDrqFro_qsqCJid0SPHp2jxSXYPc5lv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});